---
galaxy_info:
  author: Jonathan Hanson
  description: A deployment role for Matrix's Dendrite chat server.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags:
    - matrix
    - dendrite
    - chat
