---
galaxy_info:
  author: Jonathan Hanson
  description: The Smallstep Step-CA private certificate authority.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags:
    - stepca
    - smallstep
