---
# The name of the user and group to be created on the host machine,
# to own the configuration files for this service.
zwavejs2mqtt_exec_user: zwjs-exec

# The user ID and group ID to assign to the above user.  If you find that This
# UID or GID already exists on your host, adjust this to an unused value.
zwavejs2mqtt_exec_user_and_group_id: "1997"

# The version tag of the `zwavejs/zwavejs2mqtt` docker hub image.
zwavejs2mqtt_docker_image_version: "latest"

# A key/value set of environment variables and their values, which will be
# set on the docker container.
# Note: you should probably adjust the SESSION_SECRET to your own secret value
zwavejs2mqtt_environment_variables: {
  SESSION_SECRET: mysupersecretkey
}

# If set to a string, the created Docker container will attach to a
# pre-existing default Docker network, instead of creating its own.
zwavejs2mqtt_network_name: ""

# Labels to put on the application containers
zwavejs2mqtt_container_labels: []

# The path to the serial device representing the Z-Wave dongle.
# Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
# Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
zwavejs2mqtt_devices: []
# - "/dev/ttyUSB1:/dev/zwave"
