---
galaxy_info:
  author: Jonathan Hanson
  description: A simple script which maintains Route53 records pointing at the server it runs on.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags:
    - dns
