---
name: Ansible Lint

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@v4.1.0
      with:
        targets: "."
        override-deps: |
          ansible==2.12.2
          ansible-lint==5.4.0
          yamllint==1.26.3
        args: ""
