---
name: Ansible Lint

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@c37fb7b4bda2c8cb18f4942716bae9f11b0dc9bc
      with:
        targets: "."
        override-deps: |
          ansible==5.4.0
          ansible-lint==5.4.0
          yamllint==1.26.3
        args: ""
