---
- name: Ensure the admin group is present
  ansible.builtin.group:
    name: "{{ step_ca_exec_user }}"
    state: present
    gid: "{{ step_ca_exec_user_and_group_id }}"
    system: true

- name: Ensure the admin user is present
  ansible.builtin.user:
    name: "{{ step_ca_exec_user }}"
    state: present
    uid: "{{ step_ca_exec_user_and_group_id }}"
    group: "{{ step_ca_exec_user }}"
    create_home: false
    system: true
    shell: "/usr/sbin/nologin"

- name: Ensure the service config directories on the host are present
  ansible.builtin.file:
    path: "/opt/ansible-docker-compose/step_ca/"
    state: directory
    mode: "0755"

- name: Ensure the service config directories on the host are present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ step_ca_exec_user }}"
    group: "{{ step_ca_exec_user }}"
  with_items:
    - "/opt/step_ca/"

- name: Deploy and start the Docker Compose-managed service
  ansible.builtin.include_role:
    name: triplepoint.dockerized_services.docker_service
  vars:
    docker_service_name: step_ca
    docker_service_container_name: smallstep/step-ca
    docker_service_container_version: latest
    docker_service_user: root
    docker_service_config_dirs:
      - external: "/opt/step_ca"
        internal: "/home/step"
    docker_service_compose_template: "docker-compose.yml.j2"
    docker_service_environment_variables: "{{ step_ca_environment_variables }}"
    docker_service_network_name: "{{ step_ca_network_name }}"
    docker_service_container_labels: "{{ step_ca_container_labels }}"
  tags:
    - skip_ansible_lint
