---
galaxy_info:
  author: Jonathan Hanson
  description: The RTL_433 software defined radio service.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags:
    - rtl433
    - sdr
