---
galaxy_info:
  author: Jonathan Hanson
  description: The ZWaveJS2MQTT Z-wave network controller service
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags:
    - ubiquiti
    - zwavejs2mqtt
    - zwave
