---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: xenial
    image: triplepoint/ubuntu-systemd-16.04
    privileged: true
    command: /bin/bash -c "exec /sbin/init --log-target=journal 3>&1"
  - name: bionic
    image: triplepoint/ubuntu-systemd-18.04
    privileged: true
    command: /bin/bash -c "exec /sbin/init --log-target=journal 3>&1"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        home_assistant_config_secrets:
          test_secret_a: sekreta
          test_secret_b: sekretb
        home_assistant_configuration:
          homeassistant:
            name: HomePlace
            latitude: 60.0000
            longitude: -120.0000
            elevation: 1000
            unit_system: imperial
            time_zone: America/Los_Angeles
          http:
            api_password: \!secret test_secret_b

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
