---
- name: restart mosquitto
  docker_container:
    name: mosquitto
    image: "eclipse-mosquitto:{{ mosquitto_docker_version }}"
    state: started
    restart: yes
    restart_policy: always
    published_ports:
      - "8883:8883"
    volumes: "{{ _mosquitto_docker_volumes }}"
