---
# The version of the mosquitto docker image to use.
# see: https://hub.docker.com/r/library/eclipse-mosquitto/tags/
mosquitto_docker_version: "1.4.12"

# The SSL files necessary for SSL (MQTTS)
mosquitto_use_ssl: False
mosquitto_cafile: /etc/letsencrypt/live/mqtt.example.com/chain.pem
mosquitto_certfile: /etc/letsencrypt/live/mqtt.example.com/cert.pem
mosquitto_keyfile: /etc/letsencrypt/live/mqtt.example.com/privkey.pem

# A list of users, each with a `name` and `password` field.
# In practice, these values should obviously be stored protected.
mosquitto_users:
  - name: admin
    password: password1
  - name: admin2
    password: password2
  - name: admin3
    password: password3
