---
- name: Ensure the service config directories on the host are present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/opt/ansible-docker-compose/"
    - "/opt/ansible-docker-compose/rtl_433/"

- name: Ensure the config files are all present
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/ansible-docker-compose/rtl_433/{{ item }}"
    mode: 0644
  with_items:
    - start_rtl_433_mqtt_hass.sh

- name: Ensire the Dockerfile is present
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "/opt/ansible-docker-compose/rtl_433/Dockerfile"
    mode: 0644

- name: Deploy and start the Docker Compose-managed service
  ansible.builtin.include_role:
    name: triplepoint.dockerized_services.docker_compose_service
  vars:
    docker_service_name: rtl_433
    docker_service_container_name: hertzg/rtl_433
    docker_service_container_version: "{{ rtl_433_version }}-debian"
    docker_service_devices:
      - "{{ rtl_433_device_path }}"
    docker_service_command_extras:
      - "-c/config/rtl433.conf"
    docker_service_config_dirs:
      - external: "/etc/{{ docker_service_name }}"
        internal: "/config"
        templates:
          - template: rtl433.conf.j2
            dest: rtl433.conf
    docker_service_additional_volumes: "{{ rtl_433_volumes }}"
    docker_service_compose_template: "docker-compose-rtl-433.yml.j2"
  tags:
    - skip_ansible_lint
