---
- name: Ensure Docker-related python packages are present
  pip: name=docker

- name: Ensure the unifi admin group is present
  group: name="{{ unifi_exec_user }}" gid="{{ unifi_exec_user_and_group_id }}"

- name: Ensure the unifi admin user is present
  user: name="{{ unifi_exec_user }}" group="{{ unifi_exec_user }}" uid="{{ unifi_exec_user_and_group_id }}"

- name: Ensure the unifi configuration directories are present
  file: state=directory path="{{ item }}" group="{{ unifi_exec_user }}" owner="{{ unifi_exec_user }}"
  with_items:
    - /opt/unifi
    - /opt/unifi/data
    - /opt/unifi/logs

- name: Define the list of Docker volumes, used when starting the docker container
  set_fact:
    _unifi_docker_volumes:
      - "/opt/unifi/data:/usr/lib/unifi/data"
      - "/opt/unifi/logs:/usr/lib/unifi/logs"

- name: Add the certificate file directory to the list of volumes, if necessary
  set_fact:
    _unifi_docker_volumes: "{{ _unifi_docker_volumes }} + [ '{{ unifi_certfiles_dir }}:/usr/lib/unifi/cert' ]"
  when: unifi_use_ssl

- name: add any additional environment variables to the required ones
  set_fact:
    _unifi_docker_env_vars:
      UNIFI_GID: "{{ unifi_exec_user_and_group_id }}"
      UNIFI_UID: "{{ unifi_exec_user_and_group_id }}"

- name: ensure unifi is started
  docker_container:
    name: unifi
    image: "goofball222/unifi:{{ unifi_docker_image_version }}"
    state: started
    restart_policy: always
    timeout: 300
    exposed_ports:
      - 8443           # controller GUI/API, we'll expose this so an nginx proxy container can forward to it
    published_ports:
      - 3478:3478/udp    # STUN connection
      - 8080:8080/tcp    # UAP/USW/USG "to inform controller"
      - 10001:10001/udp  # UBNT access point discovery broadcasts - Local LAN only
      - 6789:6789/tcp    # throughput measurements from mobile apps (optional)
      # - 8880:8880/tcp    # HTTP portal redirect (optional)
      # - 8843:8843/tcp    # HTTPS portal redirect (optional)
    volumes: "{{ _unifi_docker_volumes }}"
    env: "{{ _unifi_docker_env_vars | combine(unifi_environment_variables) }}"
