---
# - name: Ensure the service config directories on the host are present
#   ansible.builtin.file:
#     path: "/opt/ansible-docker-compose/freshrss/"
#     state: directory
#     mode: "0755"

- name: Deploy and start the Docker Compose-managed service
  ansible.builtin.include_role:
    name: triplepoint.dockerized_services.docker_service
  vars:
    docker_service_name: freshrss
    docker_service_container_name: freshrss/freshrss
    docker_service_container_version: "{{ freshrss_version }}"
    # docker_service_config_dirs:
    #   - external: "/etc/{{ docker_service_name }}"
    #     internal: "/config"
    #     templates:
    #       - template: freshrss.conf.j2
    #         dest: freshrss.conf
    docker_service_additional_volumes: "{{ freshrss_volumes }}"
    docker_service_compose_template: "docker-compose.yml.j2"
  tags:
    - skip_ansible_lint
