---
- name: restart heimdall
  docker_container:
    name: heimdall
    hostname: heimdall
    image: "linuxserver/heimdall:{{ heimdall_docker_version }}"
    state: started
    restart_policy: always
    timeout: 300
    exposed_ports:
      - 443
    volumes: "{{ _heimdall_docker_volumes }}"
    env: "{{ _heimdall_environment_vars }}"
    restart: true
