---
- name: Ensure the service user group exists
  ansible.builtin.group:
    name: "autodns"
    state: present
    gid: "{{ autodns_uid_gid }}"
    system: true

- name: Ensure the service user exists
  ansible.builtin.user:
    name: "autodns"
    state: present
    uid: "{{ autodns_uid_gid }}"
    group: "autodns"
    create_home: false
    system: true
    shell: "/usr/sbin/nologin"

- name: Ensure the service config directories are present on the host
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "0700"
    owner: autodns
    group: autodns
  with_items:
    - "/etc/autodns/.aws"
    - "/opt/autodns"
    - "{{ autodns_ipdir }}"
    - "{{ autodns_logdir }}"

- name: Ensure logrotate is aware of the log file
  ansible.builtin.template:
    src: logrotate.autodns.j2
    dest: "/etc/logrotate.d/autodns"
    mode: "0644"
  when: autodns_enable_logrotate

- name: Ensure the AWS configuration file is present
  ansible.builtin.copy:
    src: aws_config
    dest: /etc/autodns/.aws/config
    mode: "0600"
    owner: autodns
    group: autodns
  notify: Restart autodns

- name: Ensure the AWS credentials file is present
  ansible.builtin.template:
    src: aws_credentials.j2
    dest: /etc/autodns/.aws/credentials
    mode: "0600"
    owner: autodns
    group: autodns
  notify: Restart autodns

- name: Ensure Python is available
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-virtualenv

- name: Ensure a virtualenv is created for the script, with the dependencies installed
  ansible.builtin.pip:
    name: boto3
    virtualenv: /opt/autodns/.venv
  notify: Restart autodns

- name: Ensure the script is present
  ansible.builtin.copy:
    src: "update_route53.py"
    dest: "/opt/autodns/update_route53.py"
    mode: "0644"
    owner: autodns
    group: autodns
  notify: Restart autodns

- name: Add the filename values to the environment variables
  ansible.builtin.set_fact:
    _autodns_additional_environment_variables:
      LOGDIR: "{{ autodns_logdir }}"
      LOGFILENAME: "{{ autodns_logfilename }}"
      IPDIR: "{{ autodns_ipdir }}"
      IPFILENAME: "{{ autodns_ipfilename }}"
      AWS_CONFIG_FILE: "/etc/autodns/.aws/config"
      AWS_SHARED_CREDENTIALS_FILE: "/etc/autodns/.aws/credentials"

- name: Add the filename values to the environment variables, continued
  ansible.builtin.set_fact:
    autodns_environment_variables: "{{ autodns_environment_variables | combine(_autodns_additional_environment_variables) }}"

- name: Ensure the systemd unit for the autodns service is present
  ansible.builtin.template:
    src: autodns.service.j2
    dest: /etc/systemd/system/autodns.service
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart autodns
    - Reload systemd

- name: Ensure that autodns is started and enabled
  ansible.builtin.service:
    name: autodns
    state: started
    enabled: true
