---
- name: Ensure the container user group exists
  ansible.builtin.group:
    name: "portainer"
    state: present
    gid: "{{ portainer_uid_gid }}"
    system: true

- name: Ensure the container user exists
  ansible.builtin.user:
    name: "portainer"
    state: present
    uid: "{{ portainer_uid_gid }}"
    group: "portainer"
    create_home: false
    system: true
    shell: "/usr/sbin/nologin"

- name: Ensure the data directories are present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "portainer"
    group: "portainer"
  with_items:
    - /opt/portainer/data

- name: Define the default service Docker volumes
  ansible.builtin.set_fact:
    _portainer_docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/portainer/data:/data"

- name: Append any additional volume mounts
  ansible.builtin.set_fact:
    _portainer_docker_volumes: "{{ _portainer_docker_volumes | union(portainer_additional_volumes) | sort }}"

- name: Define the default Docker environment variables
  ansible.builtin.set_fact:
    _portainer_environment_vars: {}

- name: Append any additional environment variables
  ansible.builtin.set_fact:
    _portainer_environment_vars: "{{ _portainer_environment_vars | combine(portainer_additional_environment_variables) }}"

- name: Ensure the docker-compose template directory exists
  ansible.builtin.file:
    state: directory
    path: "/opt/ansible-docker-compose/portainer"
    mode: "0755"

- name: Ensure this service's docker-compose template is present
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/ansible-docker-compose/portainer/docker-compose.yml
    mode: "0644"
    validate: docker compose -f %s config

- name: Ensure the service container(s) is/are started
  community.docker.docker_compose_v2:
    project_src: /opt/ansible-docker-compose/portainer
