---
galaxy_info:
  author: Jonathan Hanson
  description: The Mosquitto MQTT broker
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  galaxy_tags:
    - mqtt
    - mosquitto
dependencies:
  - geerlingguy.docker
