---
galaxy_info:
  author: Jonathan Hanson
  description: The Mosquitto MQTT broker
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags:
    - mqtt
    - mosquitto
