---
- name: Ensure the Docker-Compose template directory exists
  file:
    state: directory
    path: "{{ docker_service_compose_dir }}"
    mode: 0755

- name: Ensure this service's Docker-Compose template is present
  template:
    src: "{{ docker_service_compose_template }}"
    dest: "{{ docker_service_compose_dir }}/docker-compose.yml"
    mode: 0644

# - name: Ensure the latest images for the upstream container
#   community.docker.docker_image:
#     name: "{{ docker_service_parent_image }}"
#     source: pull
#     force_source: true
#     tag: "{{ docker_service_parent_image_tag }}"
#   when: docker_service_parent_image

- name: Ensure the service container(s) is/are started
  docker_compose:
    project_src: "{{ docker_service_compose_dir }}"
    pull: true
    build: true
