---
- name: Ensure the Docker-Compose template directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ docker_service_compose_dir }}"
    mode: 0755

- name: Ensure this service's Docker-Compose template is present
  ansible.builtin.template:
    src: "{{ docker_service_compose_template }}"
    dest: "{{ docker_service_compose_dir }}/docker-compose.yml"
    mode: 0644

- name: Ensure the service container(s) is/are started
  community.docker.docker_compose_v2:
    project_src: "{{ docker_service_compose_dir }}"
