---
- name: Ensure Docker-related python packages are present
  pip: name=docker

- name: Ensure the mosquitto directories are present
  file: state=directory path="{{ item }}"
  with_items:
    - "/etc/mosquitto"
    - "/opt/mosquitto/data"
    - "/var/log/mosquitto"

- name: Ensure the include Mosquitto configuration file is present
  template: src=mosquitto.conf.j2 dest=/etc/mosquitto/mosquitto.conf
  register: _mosquitto_config_file_set

- include: password_file.yml

- name: Ensure the Mosquitto Docker container is running
  docker_container:
    name: mosquitto
    image: "eclipse-mosquitto:{{ mosquitto_docker_version }}"
    restart: "{{ _mosquitto_passwords_changed or _mosquitto_config_file_set.changed }}"
    restart_policy: always
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
    volumes:
      - "/etc/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "/etc/mosquitto/passwd:/mosquitto/config/passwd"
      - "/opt/mosquitto/data:/mosquitto/data"
      - "/var/log/mosquitto:/mosquitto/log"
