---
- name: Ensure Docker-related python packages are present
  pip: name=docker

- name: Define the list of Docker volumes, used when starting the docker container
  set_fact:
    _mosquitto_docker_volumes:
      - "/etc/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro"
      - "/opt/mosquitto/data:/mosquitto/data"
      - "/var/log/mosquitto:/mosquitto/log"
      - "/etc/mosquitto/passwd:/mosquitto/config/passwd"

- name: Add the certificate file directory to the list of volumes, if necessary
  set_fact:
    _mosquitto_docker_volumes: "{{ _mosquitto_docker_volumes }} + [ '{{ mosquitto_certfiles_dir }}:/mosquitto/certs' ]"
  when: mosquitto_use_ssl

- name: Ensure the mosquitto directories are present on the host
  file: state=directory path="{{ item }}" mode=0777
  with_items:
    - "/etc/mosquitto"
    - "/opt/mosquitto/data"
    - "/var/log/mosquitto"

- name: Ensure the include Mosquitto configuration file is present
  template: src=mosquitto.conf.j2 dest=/etc/mosquitto/mosquitto.conf
  notify: restart mosquitto

- import_tasks: _var_change_detection.yml
  vars:
    _change_detection_var_name: "mosquitto_users"
    _change_detection_var: "{{ mosquitto_users }}"

- name: Delete the existing password file
  file: path="/etc/mosquitto/passwd" state=absent
  when: _change_detection_was_detected

- name: Start with an empty password file
  file: path="/etc/mosquitto/passwd" state=touch
  when: _change_detection_was_detected

- name: Write the temporary password file contents
  command: "docker run --rm -v /etc/mosquitto/passwd:/mosquitto/config/passwd eclipse-mosquitto:{{ mosquitto_docker_version }} mosquitto_passwd -b /mosquitto/config/passwd {{ item.name }} {{ item.password }}"
  with_items: "{{ mosquitto_users }}"
  no_log: True
  when: _change_detection_was_detected
  notify: restart mosquitto

- name: ensure mosquitto is started
  docker_container:
    name: mosquitto
    image: "eclipse-mosquitto:{{ mosquitto_docker_version }}"
    state: started
    restart_policy: always
    ports:
      - "8883:8883"
    volumes: "{{ _mosquitto_docker_volumes }}"
