---
- name: Delete the existing password file
  file: path="/etc/mosquitto/passwd" state=absent

- name: Start with an empty password file
  file: path="/etc/mosquitto/passwd" state=touch

- name: Write the new password file contents
  shell: "docker run -rm -v /etc/mosquitto/passwd:/mosquitto/config/passwd eclipse-mosquitto:{{ molecule_docker_version }} mosquitto_passwd -b /mosquitto/config/passwd {{ item.name }} {{ item.password }}"
  no_log: True
  with_items: "{{ molecule_users }}"
