---
# This section is a roundabout way to determine whether the mosquitti_users
# have changed since the last time this was deployed.  The end result is the
# `_mosquitto_passwords_changed` fact.
- name: Generate a hash of the users/passwords
  shell: 'echo -n "{{ mosquitto_users | to_json }}" | md5sum > /tmp/mosquitto_users_hash.new'
  register: _mosquitto_users_hash
  changed_when: False
  no_log: True

- name: Compare the hash to the hash of the last deploy
  command: "diff -q /tmp/mosquitto_users_hash.new /tmp/mosquitto_users_hash"
  register: _mosquitto_hashes_diff
  changed_when: False
  ignore_errors: True

- name: Set the variable flag for "the password file has changed"
  set_fact: _mosquitto_passwords_changed="{{ _mosquitto_hashes_diff.rc != 0 }}"

- name: Rotate the hash "current" hash file with to be the new one
  command: "mv /tmp/mosquitto_users_hash.new /tmp/mosquitto_users_hash"
  changed_when: False
