---
- name: Ensure the mDNS services are present
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - avahi-daemon
    - avahi-utils

- name: Ensure the service config directory is present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ home_assistant_host_config_dir }}"
    - "{{ home_assistant_host_config_dir }}/custom_templates"
    - "{{ home_assistant_host_config_dir }}/custom_zha_quirks"
    - "{{ home_assistant_host_config_dir }}/www"

- name: Ensure all the service configuration files are in place
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ home_assistant_host_config_dir }}/{{ item.dest }}"
    mode: "0600"
  with_items: "{{ home_assistant_template_files }}"
  notify: Restart home-assistant

- name: Ensure all the service configuration files are in place
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ home_assistant_host_config_dir }}/{{ item.dest }}"
    mode: "0600"
  with_items: "{{ home_assistant_files }}"
  notify: Restart home-assistant

- name: Ensure the service secrets file is in place
  ansible.builtin.template:
    src: "secrets.yaml.j2"
    dest: "{{ home_assistant_host_config_dir }}/secrets.yaml"
    mode: "0600"
  notify: Restart home-assistant
  no_log: true

- name: Ensure the custom cards are in place
  ansible.builtin.get_url:
    url: "{{ item.value }}"
    dest: "{{ home_assistant_host_config_dir }}/www/{{ item.key }}.js"
    mode: "0644"
  with_items: "{{ home_assistant_additional_cards | dict2items }}"

- name: Define the default service docker volumes
  ansible.builtin.set_fact:
    _home_assistant_docker_volumes:
      - "{{ home_assistant_host_config_dir }}:/config"

- name: Append any additional volume mounts
  ansible.builtin.set_fact:
    _home_assistant_docker_volumes: "{{ _home_assistant_docker_volumes | union(home_assistant_additional_volumes) | sort }}"

- name: Ensure the docker-compose template directory exists
  ansible.builtin.file:
    state: directory
    path: "/opt/ansible-docker-compose/home-assistant"
    mode: "0755"

- name: Ensure this service's docker-compose template is present
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/ansible-docker-compose/home-assistant/docker-compose.yml
    mode: "0644"
    validate: docker compose -f %s config

- name: Ensure the service container(s) is/are started
  community.docker.docker_compose_v2:
    project_src: /opt/ansible-docker-compose/home-assistant
