---
- name: Ensure Docker-related python packages are present
  pip: name=docker

- name: Ensure the home-assistant config directory is present
  file: path=/etc/home-assistant state=directory mode=0755

- name: Ensure the home-assistant secrets file is in place
  template: src=secrets.yaml.j2 dest=/etc/home-assistant/secrets.yaml mode=0600
  notify: restart home-assistant
  no_log: True

- name: Ensure the home-assistant config file is in place
  template: src=configuration.yaml.j2 dest=/etc/home-assistant/configuration.yaml mode=0600
  notify: restart home-assistant
