---
- name: Ensure Docker-related python packages are present
  pip: name=docker

- name: Ensure the home-assistant config directory is present
  file: path=/etc/home-assistant state=directory mode=0755

- name: Ensure the home-assistant secrets file is in place
  template: src=secrets.yaml.j2 dest=/etc/home-assistant/secrets.yaml mode=0600
  notify: restart home-assistant
  no_log: True

- name: Ensure the home-assistant config file is in place
  template: src=configuration.yaml.j2 dest=/etc/home-assistant/configuration.yaml mode=0600
  notify: restart home-assistant

- name: Define the default home-assistant docker volumes
  set_fact:
    _home_assistant_docker_volumes:
      - "/etc/home-assistant:/config"
      - "/etc/localtime:/etc/localtime:ro"

- name: Append any additional volume mounts
  set_fact:
    _home_assistant_docker_volumes: "{{ _home_assistant_docker_volumes }} + {{ home_assistant_additional_volumes }}"

- name: ensure home-assistant is started
  docker_container:
    name: home-assistant
    image: "homeassistant/home-assistant:{{ home_assistant_docker_version }}"
    state: started
    restart_policy: always
    timeout: 300
    ports:
      - "{{ home_assistant_server_port }}:8123" # Web admin panel
    volumes: "{{ _home_assistant_docker_volumes }}"
