---
# What version of the homeassistant/home-assistant docker image should we
# install?
home_assistant_docker_version: 0.98.5

# A list of src and dest values that define configuration templates to be
# rendered into the {{home_assistant_host_config_dir}} configuration directory.
# The `dest` values should be file names without the path, and the `src`
# values should be any resolveable Ansible template file path.
home_assistant_template_files:
  - src: configuration.yaml.j2
    dest: configuration.yaml
  - src: automations.yaml.j2
    dest: automations.yaml
  - src: customize.yaml.j2
    dest: customize.yaml
  - src: groups.yaml.j2
    dest: groups.yaml
  - src: scripts.yaml.j2
    dest: scripts.yaml

# A list of key/value pairs, suitable for being a reference secrets file
# to be referenced by home-assistant's configuration file.
# see https://home-assistant.io/docs/configuration/secrets/
home_assistant_config_secrets: []
# - somepassword: sooper_sekret

# A list of additional volumes to mount into the docker container.  This is
# useful for things like SSL certificates and custom css/image assets.
home_assistant_additional_volumes: []
# - "/some/directory:/some/mount:ro"
# - "/some/file.yml:/some/mount/file.yml:ro"

# A key/value set of environment variables and their values, which will be
# set on the docker container.
home_assistant_environment_variables:
  TZ: America/Los_Angeles

# Where on the host machine should the configuration directory be set.
# This path gets volume-mounted into the Docker container, and is the
# primary location home-assistant reads and writes its configuration.
home_assistant_host_config_dir: "/etc/home-assistant"
