---
- name: restart home-assistant
  docker_container:
    name: home-assistant
    image: "homeassistant/home-assistant:{{ home_assistant_docker_version }}"
    state: started
    restart: yes
    restart_policy: always
    timeout: 300
    ports:
      - "{{ home_assistant_server_port }}:8123" # Web admin panel
    volumes: "{{ _home_assistant_docker_volumes }}"
