---
- name: Ensure the container user group exists
  ansible.builtin.group:
    name: "mozsyncserverrs"
    state: present
    gid: "{{ mozilla_syncserver_rs_uid_gid }}"
    system: true

- name: Ensure the container user exists
  ansible.builtin.user:
    name: "mozsyncserverrs"
    state: present
    uid: "{{ mozilla_syncserver_rs_uid_gid }}"
    group: "mozsyncserverrs"
    create_home: false
    system: true
    shell: "/usr/sbin/nologin"

- name: Ensure the config directory is present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "mozsyncserverrs"
    group: "mozsyncserverrs"
  with_items:
    - "{{ mozilla_syncserver_rs_working_directory }}"
    - "{{ mozilla_syncserver_rs_working_directory }}/initdb.d/"

- name: Ensure the docker-compose template directory exists
  ansible.builtin.file:
    state: directory
    path: "/opt/ansible-docker-compose/mozilla-syncserver-rs"
    mode: "0755"

- name: Ensure that the support files for the docker build are present (cont.)
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ mozilla_syncserver_rs_working_directory }}/initdb.d/{{ item }}"
    mode: "0644"
    owner: "mozsyncserverrs"
    group: "mozsyncserverrs"
  with_items:
    - db-init.sql
  notify: Restart mozilla-syncserver-rs

- name: Ensure this service's docker-compose template is present
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/ansible-docker-compose/mozilla-syncserver-rs/docker-compose.yml
    mode: "0644"
    validate: docker compose -f %s config
  notify: Restart mozilla-syncserver-rs

- name: Ensure the service container(s) is/are started
  community.docker.docker_compose_v2:
    project_src: /opt/ansible-docker-compose/mozilla-syncserver-rs
