---
galaxy_info:
  author: Jonathan Hanson
  description: Deployment for a Heimdall.site docker container
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags: []
