---
galaxy_info:
  role_name: home_assistant
  author: Jonathan Hanson
  description: A deployment role for Home-Assistant.io.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
  galaxy_tags:
    - homeassistant
    - homeautomation
dependencies: []
